# Generated by Django 3.0.8 on 2020-10-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('locked', models.BooleanField(blank=True, default=False, null=True)),
                ('createTime', models.DateTimeField(blank=True, null=True)),
                ('updateTime', models.DateTimeField(blank=True, null=True)),
                ('itemIdentifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('effectiveDate', models.DateField(max_length=20)),
                ('expirationDate', models.DateField(blank=True, max_length=20, null=True)),
                ('BranchType', models.CharField(choices=[('local', 'Local'), ('main', 'Main')], default='local', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('locked', models.BooleanField(blank=True, default=False, null=True)),
                ('createTime', models.DateTimeField(blank=True, null=True)),
                ('updateTime', models.DateTimeField(blank=True, null=True)),
                ('itemIdentifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('effectiveDate', models.DateField(max_length=20)),
                ('expirationDate', models.DateField(blank=True, max_length=20, null=True)),
            ],
            options={
                'select_on_save': True,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('locked', models.BooleanField(blank=True, default=False, null=True)),
                ('createTime', models.DateTimeField(blank=True, null=True)),
                ('updateTime', models.DateTimeField(blank=True, null=True)),
                ('itemIdentifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('effectiveDate', models.DateField(max_length=20)),
                ('expirationDate', models.DateField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealerLocation',
            fields=[
                ('purge', models.BooleanField(blank=True, default=False, null=True)),
                ('itemIdentifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('locationName', models.CharField(blank=True, max_length=255)),
                ('addressLine1', models.CharField(blank=True, max_length=255)),
                ('addressLine2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postCode', models.CharField(blank=True, max_length=255)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='refrest.Dealer')),
            ],
            options={
                'select_on_save': True,
            },
        ),
    ]
