# Generated by Django 3.0.8 on 2020-10-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('locked', models.BooleanField(blank=True, default=False, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('item_uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('effective_date', models.DateField(max_length=20)),
                ('expiration_date', models.DateField(blank=True, max_length=20, null=True)),
                ('BranchType', models.CharField(choices=[('local', 'Local'), ('main', 'Main')], default='local', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('locked', models.BooleanField(blank=True, default=False, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('item_uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('effective_date', models.DateField(max_length=20)),
                ('expiration_date', models.DateField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('locked', models.BooleanField(blank=True, default=False, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('item_uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('effective_date', models.DateField(max_length=20)),
                ('expiration_date', models.DateField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('post_code', models.CharField(blank=True, max_length=255)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_locations', to='refrest.Dealer')),
            ],
        ),
    ]
